# ---
---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:8
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra

# dependency:
#   name: galaxy
# driver:
#   name: docker
# lint: |
#   set -e
#   yamllint -c molecule/default/.yamllint .
#   ansible-lint -x meta-incorrect,meta-no-info,package-latest,yaml
# platforms:
#   - name: instance-centos
#     image: "spurin/diveintoansible:centos"
#     command: "/lib/systemd/systemd"
#     volumes:
#       - /sys/fs/cgroup:/sys/fs/cgroup:ro
#     privileged: true
#     pre_build_image: true
#   - name: instance-ubuntu
#     image: "spurin/diveintoansible:ubuntu"
#     command: "/lib/systemd/systemd"
#     volumes:
#       - /sys/fs/cgroup:/sys/fs/cgroup:ro
#     privileged: true
#     pre_build_image: true
# provisioner:
#   name: ansible
# verifier:
#   name: ansible
# scenario:
#   test_sequence:
#     - dependency
#     - lint
#     - cleanup
#     - destroy
#     - syntax
#     - create
#     - prepare
#     - converge
# #    - idempotence
#     - side_effect
#     - verify
#     - cleanup
#     - destroy
